/* pense-bem-esp32 — the 1988 Tectoy "Pense Bem", book mode, on a LilyGO T-Display V1.1.
 *
 *   SELECT = the RIGHT button (GPIO35)  short = next value · HOLD = auto-repeat
 *   OK     = the LEFT  button (GPIO0)   short = confirm. ⚠ NO HOLD GESTURE, EVER.
 *
 * ⚠ Every on-screen hint is drawn on the SIDE of the button it refers to, because
 *   the board has two unlabelled buttons and a logical name is a 50/50 guess.
 *   (Learned the hard way — see README, "the hint pointed at the wrong button".)
 *
 * THIS SKETCH OWNS NO RULES. It maps two buttons and draws pixels.
 *   pensebem.h  the answer formula   (host-proven: formula-test/)
 *   pbgame.h    the session rules    (host-proven: game-test/, written test-first)
 * Anything a host test could check does not belong in this file.
 *
 * ⚠ NEVER paste the seed or offset constants in here. formula-test/run.sh stage 1
 *   fails if they appear anywhere except pensebem.h — that grep is the only thing
 *   keeping "the tests read the shipped code" true.
 *
 * ⚠ WIFI IS FOR OTA REFLASHING, AND FOR ONE MESSAGE. No game path reads it.
 *   The answer is pure arithmetic; the game runs identically with the AP down.
 *   If a change ever makes gameplay depend on WiFi, that is a different device.
 *
 *   ⚠ THIS FILE USED TO SAY "no relay, no server, no telemetry", AND THAT IS NO
 *   LONGER TRUE — said out loud here because the old wording instructed whoever
 *   changed it to do exactly that. Since 2026-08-03 the board POSTs once per
 *   boot to api.pense-bem-wars.com: a random UUID it generated itself, plus the
 *   build stamp. Nothing else, ever. It is disclosed on screen at first boot in
 *   Portuguese and English, documented in the README, and compiled out entirely
 *   by PB_PHONE_HOME 0. See pbhello.h for what is sent and why it exists.
 *   Gameplay does NOT depend on it: the POST runs on its own task, is attempted
 *   exactly once, and is never retried in a loop.
 *
 * SCARS — every one of these cost a debugging session:
 *   ⚠ GPIO0 IS A STRAPPING PIN. Held LOW at boot it enters USB download mode, and
 *     holding it during a blocking call can starve the task watchdog. It gets
 *     short presses only; every hold gesture lives on GPIO35.
 *   ⚠ GPIO35 IS INPUT-ONLY WITH NO INTERNAL PULL-UP. pinMode(35, INPUT_PULLUP)
 *     compiles, runs, and configures nothing. The board has an external one.
 *   ⚠ TFT_eSPI FONTS 6/7/8 ARE DIGIT/CLOCK FACES, NOT ASCII. Composed text uses
 *     FreeFonts, and every centred string goes through centreFit() so a long one
 *     shrinks instead of losing its first and last letters.
 *   ⚠ ledcAttach AFTER tft.init(). tft.init() does pinMode+digitalWrite on its
 *     backlight pin and clobbers a PWM mux attached before it.
 *   ⚠ Declare types ABOVE the first function. The Arduino build auto-generates
 *     prototypes at the top of every .ino, so a struct defined halfway down
 *     yields an error about a prototype you never wrote.
 *
 * Beerware Rev 42 applies to the constants in pensebem.h — see NOTICE.
 */
#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <ESPmDNS.h>
#include <ArduinoOTA.h>
#include <TFT_eSPI.h>
#include <Preferences.h>
#include <esp_random.h>

#include "secrets.h"
#include "version.h"   /* generated by build.sh; PB_VERSION */
#include "pensebem.h"
#include "pbgame.h"
#include "pbhello.h"

/* ⚠ TYPES MUST BE DECLARED BEFORE ANY FUNCTION THAT USES THEM, up here next to
   the includes. The Arduino build auto-generates prototypes for every function
   in a .ino and inserts them at the TOP of the file — so a struct defined
   halfway down yields "'Note' does not name a type" from a prototype the author
   never wrote and cannot see. */
struct Note { uint16_t hz; uint16_t ms; };   /* hz == 0 is a rest */

// ---- constants -------------------------------------------------------------

/* ⚠ The mDNS/OTA name deliberately does NOT track the sketch filename. Renaming
   this string renames the board on the network, which breaks `./build.sh ota`
   until the board is reflashed over USB — a chicken-and-egg you do not want. */
static const char *HOSTNAME = "esp32-pense-bem";

// ⚠ PHYSICAL SIDES, AND THE UI DEPENDS ON THEM. With setRotation(1) the sibling
//   sketch's own comment is authoritative: GPIO0 is the LEFT button, GPIO35 is
//   the RIGHT one. Every on-screen hint is therefore drawn on the side of the
//   button it refers to — LEFT-aligned text means the left button, RIGHT-aligned
//   means the right one. POSITION IS THE LABEL.
//
//   ⚠⚠ This was BACKWARDS on first flash: "SELECT" was drawn left-aligned while
//   SELECT is physically the right button. A tester held the left one for a while
//   and nothing happened — correct behaviour (OK has no hold gesture, it is a
//   strapping pin) reached through a hint pointing at the wrong button. Naming a
//   logical button on a device with two unlabelled physical ones is a 50/50
//   guess; placing the hint under the button is not.
static const int PIN_SELECT = 35;  // RIGHT button. input-only, EXTERNAL pull-up
static const int PIN_OK     = 0;   // LEFT button. strapping pin — short press only
static const int PIN_BL     = 4;   // backlight, LEDC

// ⚠ Set to -1 and every sound call compiles out — the board works with the wires
//   pulled, which is exactly what happens if the arriving case will not close
//   over them. GPIO21 is the repo's documented free pin on this board.
#define PB_BUZZER_PIN 21

/* ── SAY HELLO ONCE ────────────────────────────────────────────────────────
   ⚠ SET TO 0 AND EVERY LINE OF IT COMPILES OUT — no request, no UUID, no
   consent screen, no HTTPClient linked. Deliberately the same shape as
   PB_BUZZER_PIN -1 above: one define, whole feature gone.

   That switch is not a preference toggle. It is the board owner's own defence.
   The hostname below is compiled into this binary, so if the domain ever lapses
   every board still running this firmware would POST to whoever registers it
   next — and the owner cannot be reflashed remotely by anyone but themselves.
   Registration is paid to 2027-08-04 with auto-renew on; this switch is what
   makes that a promise the owner does not have to take on trust.

   What is sent, in full: a random UUID this board generated on first boot, and
   PB_VERSION. Not the MAC, not a score, not a book, not an answer. */
#define PB_PHONE_HOME 1
#define PB_API_HOST   "api.pense-bem-wars.com"

/* ── the shared hotspot ────────────────────────────────────────────────────
   The board prefers a hotspot named "pense-bem" and falls back to whatever is
   in secrets.h. The point is that a board can be handed to someone, taken to a
   friend's house or carried to a meetup and still reach the counter without
   anyone editing firmware — you bring the network with you.

   ⚠ THIS PASSWORD IS PUBLIC AND THAT IS FINE, BUT KNOW WHY.
   It is compiled into an open-source binary, so it is extractable by anyone who
   wants it, and anyone can stand up an access point with this name. A board
   joining a hostile one gets to: see a fabricated board count, and receive a
   POST that goes nowhere. It cannot be reflashed — OTA is password-protected
   with a per-board secret from secrets.h — and the only thing it transmits is a
   random UUID and a version string. The exposure is real and it is tiny. Do not
   ever put anything on this network that assumes the network is trusted.

   ⚠ NEVER USE WiFiMulti HERE. Its run() blocks for seconds while it scans, and
   this sketch's first rule is that WiFi never blocks the game. The alternation
   below is non-blocking: begin() is fire-and-forget and wifiTick() just retimes
   it. The game runs identically with both networks down. */
#define PB_HOTSPOT_SSID "pense-bem"
#define PB_HOTSPOT_PASS "0192837465"
#define PB_WIFI_SWAP_MS 30000   /* ⚠ MUST exceed association + DHCP, or each retry aborts the last */

static const uint16_t W = 240, H = 135;   // setRotation(1)

static const uint32_t DEBOUNCE_MS   = 60;
static const uint32_t REPEAT_WAIT_MS= 500;  // hold this long before auto-repeat
static const uint32_t REPEAT_FAST_MS= 220;  // then one step every…
static const uint32_t REPEAT_TURBO_MS=90;   // …accelerating after REPEAT_ACCEL_MS
static const uint32_t REPEAT_ACCEL_MS=2000;

static const uint32_t JUDGE_HOLD_MS = 1200; // CERTO / ERRADO dwell
static const uint32_t REVEAL_HOLD_MS= 2600; // the 3rd-try reveal
static const uint32_t BAD_HOLD_MS   = 1600; // a refused code, with its reason

// ⚠ DELIBERATE DEVIATION FROM THE 1988 TOY, DO NOT "FIX" IT BACK. The original
//   auto-powered-off after 3 minutes. Three minutes to read a printed question,
//   find the page and press through is not enough for this user, and a timeout
//   destroying 25 minutes of score is the worst thing this device can do.
static const uint32_t IDLE_MENU_MS  = 180000;  // 3 min — faithful
static const uint32_t IDLE_GAME_MS  = 600000;  // 10 min — deliberate

static const uint8_t BL_ON = 140;

// Colours. cyan = the current selection, and nothing else uses it.
#define C_BG      TFT_BLACK
#define C_TEXT    TFT_WHITE
#define C_DIM     0x8410
#define C_SEL     TFT_CYAN
#define C_RIGHT   0x07E0
#define C_WRONG   0xF800
#define C_TRY     0xFD20

// ---- state -----------------------------------------------------------------

enum Screen { SC_STANDBY, SC_CODE, SC_BAD, SC_QUESTION, SC_JUDGE, SC_SCORE };

TFT_eSPI tft = TFT_eSPI();
Preferences prefs;

static PbGame  game;
static Screen  screen      = SC_STANDBY;
static uint32_t screenAt   = 0;   // when the current screen was entered
static uint32_t lastInput  = 0;   // idle timer
static String  lastDrawn;         // render cache

static int  digits[3] = {0, 0, 0};// the three code positions, as VALUE INDEXES
static int  pos       = 0;        // which position is being edited
static int  answerSel = 0;        // 0..3 -> A..D
static PbVerdict lastVerdict = PB_IGNORED;
static const char *badReason = "";

static int  lastScore = -1;       // last completed session, for STANDBY
static int  lastBook = 0, lastSection = 0;
static bool muted = false;

// Value lists per code position. ⚠ The section digit gets SEVEN values, not ten:
// only 1-6 are legal, so offering 0/7/8/9 is offering a guaranteed refusal.
// Last entry of each list is the ERASE value.
static const char *VALS[3] = { "0123456789<", "0123456789<", "123456<" };
static int valCount(int p) { return (int)strlen(VALS[p]); }
static char valAt(int p, int i) { return VALS[p][i]; }

// ---- sound -----------------------------------------------------------------
//
// ⚠ NO delay() ANYWHERE IN HERE. A blocking jingle freezes the button scan and
//   the idle timer, and the 3-tries path is exactly where that hurts.

static const Note SFX_STEP[]   = { {1200, 25} };
static const Note SFX_OK[]     = { {1600, 40} };
static const Note SFX_RIGHT[]  = { {880, 90}, {1320, 140} };
static const Note SFX_WRONG[]  = { {200, 260} };
static const Note SFX_REVEAL[] = { {520, 110}, {0, 60}, {392, 220} };
static const Note SFX_BAD[]    = { {160, 90}, {0, 50}, {160, 90} };
/* Boot self-test. Its whole job is to answer "did the buzzer wiring work?" the
   instant the board powers up, with nothing to navigate to. Deliberately three
   rising notes so it cannot be confused with SFX_RIGHT (two notes) or any other
   cue. ⚠ It RESPECTS mute — a muted toy that chirps on every power-up is a bug,
   not a feature — so if you hear nothing, check the standby screen: it states
   the mute state in words. */
static const Note SFX_BOOT[]   = { {660, 70}, {880, 70}, {1320, 120} };
/* One note per answer box as it sweeps in — A B C D, rising. */
static const Note SFX_SPLASH_A[] = { {523, 90} };
static const Note SFX_SPLASH_B[] = { {659, 90} };
static const Note SFX_SPLASH_C[] = { {784, 90} };
static const Note SFX_SPLASH_D[] = { {1047, 220} };
// The four end-of-session songs, one per score band — the toy really had four.
static const Note SONG_0[] = { {523,140},{659,140},{784,140},{1047,320} };           // OTIMO
static const Note SONG_1[] = { {523,150},{659,150},{784,300} };                      // MUITO BEM
static const Note SONG_2[] = { {440,170},{523,170},{440,300} };                      // QUASE LA
static const Note SONG_3[] = { {392,200},{330,200},{262,380} };                      // TENTE MAIS

static const Note *sq = nullptr;
static uint8_t sqLen = 0, sqIdx = 0;
static uint32_t sqAt = 0;
static bool sqOn = false;

static void soundStop()
{
#if PB_BUZZER_PIN >= 0
    ledcWriteTone(PB_BUZZER_PIN, 0);
#endif
    sq = nullptr; sqOn = false;
}

static void soundPlay(const Note *seq, uint8_t len)
{
#if PB_BUZZER_PIN >= 0
    if (muted) { return; }
    sq = seq; sqLen = len; sqIdx = 0; sqAt = 0; sqOn = false;
#else
    (void)seq; (void)len;
#endif
}
#define PLAY(x) soundPlay((x), (uint8_t)(sizeof(x) / sizeof((x)[0])))

static void soundTick()
{
#if PB_BUZZER_PIN >= 0
    if (!sq) { return; }
    uint32_t now = millis();
    if (!sqOn) {
        if (sqIdx >= sqLen) { soundStop(); return; }
        ledcWriteTone(PB_BUZZER_PIN, sq[sqIdx].hz);   // hz 0 = a rest
        sqAt = now; sqOn = true;
        return;
    }
    if (now - sqAt >= sq[sqIdx].ms) {
        ledcWriteTone(PB_BUZZER_PIN, 0);
        sqIdx++; sqOn = false;
    }
#endif
}

// ---- drawing helpers -------------------------------------------------------

static void centre(const char *s, int y)
{
    tft.setTextDatum(TC_DATUM);
    tft.drawString(s, W / 2, y);
}

static void small()  { tft.setFreeFont(&FreeSans9pt7b);      }
static void medium() { tft.setFreeFont(&FreeSansBold12pt7b); }
static void large()  { tft.setFreeFont(&FreeSansBold18pt7b); }
static void huge()   { tft.setFreeFont(&FreeSansBold24pt7b); }

/* ⚠ CLIPPING IS DESIGNED OUT, NOT HAND-TUNED. The first flash rendered
   "PENSE BEM" at 24pt and it ran off BOTH edges of the 240px panel — invisible
   to every host test, caught on the desk camera in one frame. Guessing a font
   size per string just moves the guess. This picks the largest face that
   MEASURES small enough for the width it is given, so a longer string degrades
   instead of losing its first and last letters.

   Same family as the font-6 scar this board already carries: the failure is
   silent and only glass shows it. */
/* ⚠ TIER IS A CEILING, AND OMITTING IT WAS A BUG. centreFit picks the LARGEST
   face that fits the WIDTH — correct for a title, wrong for everything else.
   "SOM LIGADO" is short, so it fitted at 24pt, rendered ~34px tall, and ran
   straight through the hint row below it. Nothing is layered on this panel;
   what actually has to hold is a VERTICAL BUDGET, and width-fitting alone
   cannot enforce one.

   T_TITLE 24pt (~34px) · T_BIG 18pt (~26px) · T_MED 12pt (~18px) · T_SMALL 9pt (~13px) */
#define T_TITLE 0
#define T_BIG   1
#define T_MED   2
#define T_SMALL 3

static void centreFit(const char *s, int y, int maxW, int tier)
{
    if (tier <= T_TITLE) { huge();   if (tft.textWidth(s) <= maxW) { centre(s, y); return; } }
    if (tier <= T_BIG)   { large();  if (tft.textWidth(s) <= maxW) { centre(s, y); return; } }
    if (tier <= T_MED)   { medium(); if (tft.textWidth(s) <= maxW) { centre(s, y); return; } }
    small(); centre(s, y);
}

/* ⚠ TWO HINTS AT THE SAME y CAN COLLIDE, AND centreFit() DOES NOT PROTECT THEM
   — neither one is centred. Shipped exactly that way: the standby row rendered
   "< OK comecisegure = som >" because "< OK comeca" and "segure = som >" ran into
   each other in the middle. Invisible to every test; obvious on video.

   So the same treatment as centreFit: MEASURE, then step down a face until the
   pair fits with a gap. A long hint shrinks instead of eating its neighbour.
   ⚠ The fallback is built-in font 1, which IS ASCII — fonts 6/7/8 are
   digit/clock faces and would render letters as garbage. */
static void drawHints(const char *l, const char *r, int y)
{
    const int GAP = 8;

    small();
    if (tft.textWidth(l) + tft.textWidth(r) + GAP > W) {
        tft.setFreeFont(NULL);
        tft.setTextFont(1);
        tft.setTextSize(1);
    }
    tft.setTextDatum(TL_DATUM); tft.drawString(l, 6, y);
    tft.setTextDatum(TR_DATUM); tft.drawString(r, W - 6, y);
    small();
}

static const char *BANDS[4] = { "OTIMO", "MUITO BEM", "QUASE LA", "TENTE MAIS" };

// ---- splash ----------------------------------------------------------------
//
// ⚠ This BLOCKS, and that is fine here and nowhere else: nothing else is running
//   at boot, there is no watchdog armed, and no input is meaningful yet. It still
//   pumps soundTick() on every pass, because the note player is non-blocking by
//   design and would otherwise go silent for the whole animation.
//
// ⚠ Skippable. A splash you cannot skip becomes annoying by the twentieth boot —
//   TAP OK during it to cut straight to standby. ⚠ Tap, do not hold from
//   power-on: OK is GPIO0, and holding it through reset puts the ESP32 into USB
//   download mode instead of running this firmware at all.

/* ⚠ SKIP MEANS "PRESSED DURING", NOT "IS DOWN". The first version aborted the
   moment GPIO0 read LOW — so a finger resting on the left button, or a button
   still down from the reset, cancelled the whole animation instantly and the
   board appeared to jump straight to standby. Latch the initial state and only
   treat a HIGH->LOW transition as intent. */
static bool splashArmed;      /* true once OK has been seen released */

static bool splashSkip()
{
    bool down = (digitalRead(PIN_OK) == LOW);

    if (!splashArmed) {
        if (!down) { splashArmed = true; }   /* released -> a press now counts */
        return false;
    }
    return down;
}

/* Sleeps while keeping sound alive; returns true if the user asked to skip. */
static bool splashWait(uint32_t ms)
{
    uint32_t t0 = millis();
    while (millis() - t0 < ms) {
        soundTick();
        if (splashSkip()) { return true; }
        delay(4);
    }
    return false;
}

/* PARTICLE ASSEMBLE — dust converges into the title, the way the LilyGO demo
   assembles a face. Our flavour: the letters are the attractor.
 *
 * HOW: render the title once into an off-screen sprite, harvest the coordinates
 * of its lit pixels as TARGETS, scatter that many particles at random, then ease
 * each one toward its target. No font metrics are hard-coded and no positions
 * are guessed — the shape IS the rendered text, so this cannot drift out of
 * alignment with what the standby screen draws.
 *
 * ⚠ That is also why v1 and v2 were thrown away. Both positioned elements from
 *   independent constants and collided. Here there is exactly one shape, and it
 *   is derived from the thing it depicts.
 *
 * COST: the sprite is freed before the animation runs. Particles are int16 fixed
 * point (4 fractional bits) — no float, no allocation in the loop. Each frame
 * writes 2 pixels per particle (erase old, draw new) rather than repainting the
 * screen, which is what keeps it smooth over SPI. */

#define PB_MAXP 900

static int16_t pTx[PB_MAXP], pTy[PB_MAXP];   /* target, whole pixels   */
static int16_t pX[PB_MAXP],  pY[PB_MAXP];    /* current, <<4 fixed pt  */
static uint16_t pC[PB_MAXP];                 /* per-particle shade     */
static int pN;

static const uint16_t DUST[] = { 0xFFFF, 0xCE7F, 0x9CDF, 0x6B7F };

/* Harvest lit pixels of the title into the target arrays. */
static void splashBuildTargets()
{
    const char *TITLE = "PENSE BEM";
    const int SH = 46;                         /* sprite height */
    TFT_eSprite spr = TFT_eSprite(&tft);
    int x, y, step, lit = 0;

    pN = 0;
    spr.setColorDepth(8);
    if (!spr.createSprite(W, SH)) { return; }  /* out of RAM -> pN stays 0 */
    spr.fillSprite(TFT_BLACK);
    spr.setTextColor(TFT_WHITE);
    huge();
    spr.setFreeFont(&FreeSansBold24pt7b);
    if (spr.textWidth(TITLE) > W - 10) { spr.setFreeFont(&FreeSansBold18pt7b); }
    spr.setTextDatum(MC_DATUM);
    spr.drawString(TITLE, W / 2, SH / 2);

    for (y = 0; y < SH; y++) {
        for (x = 0; x < W; x++) { if (spr.readPixel(x, y)) { lit++; } }
    }
    step = lit > PB_MAXP ? (lit / PB_MAXP) + 1 : 1;

    lit = 0;
    for (y = 0; y < SH && pN < PB_MAXP; y++) {
        for (x = 0; x < W && pN < PB_MAXP; x++) {
            if (!spr.readPixel(x, y)) { continue; }
            if ((lit++ % step) != 0) { continue; }
            pTx[pN] = x;
            pTy[pN] = y + 30;                  /* place the block on screen */
            pN++;
        }
    }
    spr.deleteSprite();                        /* ⚠ freed BEFORE animating */
}

static void playSplash()
{
    int i, f;

    tft.fillScreen(C_BG);
    splashArmed = false;             /* a button already down must not cancel us */
    randomSeed(micros());
    splashBuildTargets();

    if (pN == 0) {                             /* no RAM for the sprite: degrade */
        centreFit("PENSE BEM", 44, W - 8, T_TITLE);
        splashWait(700);
        tft.fillScreen(C_BG);
        return;
    }

    for (i = 0; i < pN; i++) {
        pX[i] = (int16_t)(random(0, W) << 4);
        pY[i] = (int16_t)(random(0, H) << 4);
        pC[i] = DUST[random(0, 4)];
    }

    /* converge — ease-out, so it rushes in then settles */
    for (f = 0; f < 46; f++) {
        for (i = 0; i < pN; i++) {
            int ox = pX[i] >> 4, oy = pY[i] >> 4;
            tft.drawPixel(ox, oy, C_BG);
            pX[i] += (int16_t)(((int32_t)(pTx[i] << 4) - pX[i]) * 30 >> 8);
            pY[i] += (int16_t)(((int32_t)(pTy[i] << 4) - pY[i]) * 30 >> 8);
            tft.drawPixel(pX[i] >> 4, pY[i] >> 4, pC[i]);
        }
        if (f == 6)  { PLAY(SFX_SPLASH_A); }
        if (f == 16) { PLAY(SFX_SPLASH_B); }
        if (f == 26) { PLAY(SFX_SPLASH_C); }
        if (f == 36) { PLAY(SFX_SPLASH_D); }
        if (splashWait(10)) { tft.fillScreen(C_BG); return; }
    }

    /* settle: snap to target, all one colour, so the word reads cleanly */
    for (i = 0; i < pN; i++) {
        tft.drawPixel(pX[i] >> 4, pY[i] >> 4, C_BG);
        tft.drawPixel(pTx[i], pTy[i], TFT_WHITE);
    }
    if (splashWait(520)) { tft.fillScreen(C_BG); return; }

    /* breathe once, the way the reference keeps shimmering */
    for (f = 0; f < 2; f++) {
        for (i = 0; i < pN; i += 3) { tft.drawPixel(pTx[i], pTy[i], DUST[2]); }
        if (splashWait(90)) { tft.fillScreen(C_BG); return; }
        for (i = 0; i < pN; i += 3) { tft.drawPixel(pTx[i], pTy[i], TFT_WHITE); }
        if (splashWait(90)) { tft.fillScreen(C_BG); return; }
    }

    splashWait(200);
    tft.fillScreen(C_BG);
}

// ---- screens ---------------------------------------------------------------

static void drawStandby()
{
    /* ⚠ VERTICAL BUDGET, 135px tall. Every band states the face it uses, because
       the heights are what must not collide:
         y   2  version stamp   font1  ~8px  -> 10
         y  16  title           <=24pt ~34px -> 50   ⚠ was y=10 and the stamp
                                                      overlapped "BEM". 6px gap now.
         y  56  last score       9pt   ~13px -> 69
         y  76  start hint       9pt   ~13px -> 89
         y  94  sound state      9pt   ~13px -> 107
         y 116  button hints     9pt   ~13px -> 129   (H = 135) */
    tft.fillScreen(C_BG);

    tft.setFreeFont(NULL); tft.setTextFont(1); tft.setTextSize(1);
    tft.setTextColor(C_DIM, C_BG);
    tft.setTextDatum(TR_DATUM); tft.drawString(PB_VERSION, W - 4, 2);

    tft.setTextColor(C_TEXT, C_BG);
    centreFit("PENSE BEM", 16, W - 8, T_TITLE);

    if (lastScore >= 0) {
        char buf[40];
        snprintf(buf, sizeof(buf), "ultimo  L%02d S%d  %d pts", lastBook, lastSection, lastScore);
        tft.setTextColor(C_DIM, C_BG);
        centreFit(buf, 56, W - 8, T_SMALL);
    }

    tft.setTextColor(C_SEL, C_BG);
    centreFit("OK PARA COMECAR", 76, W - 8, T_SMALL);

    tft.setTextColor(muted ? C_WRONG : C_DIM, C_BG);
    centreFit(muted ? "SOM DESLIGADO" : "SOM LIGADO", 94, W - 8, T_SMALL);

    tft.setTextColor(C_DIM, C_BG);
    drawHints("< OK", "segure = som >", 116);
}

static void drawCode()
{
    tft.fillScreen(C_BG);
    small(); tft.setTextColor(C_DIM, C_BG);
    tft.setTextDatum(TL_DATUM); tft.drawString("CODIGO DO LIVRO", 6, 4);
    tft.setTextDatum(TR_DATUM);
    tft.drawString(pos == 2 ? "SECAO" : "LIVRO", W - 6, 4);
    tft.drawFastHLine(0, 26, W, C_DIM);

    for (int i = 0; i < 3; i++) {
        int x = 46 + i * 56;
        huge();
        if (i < pos) {
            tft.setTextColor(C_TEXT, C_BG);
            char c[2] = { valAt(i, digits[i]), 0 };
            tft.setTextDatum(TC_DATUM); tft.drawString(c, x, 40);
        } else if (i == pos) {
            char v = valAt(i, digits[i]);
            tft.drawRect(x - 24, 34, 48, 52, C_SEL);
            tft.setTextColor(C_SEL, C_BG);
            char c[2] = { v == '<' ? '<' : v, 0 };
            tft.setTextDatum(TC_DATUM); tft.drawString(c, x, 40);
        } else {
            tft.setTextColor(C_DIM, C_BG);
            tft.setTextDatum(TC_DATUM); tft.drawString("-", x, 40);
        }
    }
    tft.setTextColor(C_DIM, C_BG);
    drawHints(valAt(pos, digits[pos]) == '<' ? "< OK apaga" : "< OK confirma",
              "muda >", H - 20);
}

static void drawBad()
{
    tft.fillScreen(C_BG);
    tft.setTextColor(C_WRONG, C_BG);
    centreFit("CODIGO INVALIDO", 26, W - 8, T_BIG);
    tft.setTextColor(C_TEXT, C_BG);
    centreFit(badReason, 72, W - 8, T_SMALL);
}

static void drawQuestion()
{
    char buf[32];
    tft.fillScreen(C_BG);
    small();
    tft.setTextColor(C_DIM, C_BG);
    tft.setTextDatum(TL_DATUM);
    snprintf(buf, sizeof(buf), "Q%02d/%02d", game.index + 1, game.n);
    tft.drawString(buf, 6, 4);

    // ⚠ THE ABSOLUTE QUESTION NUMBER IS LOAD-BEARING. Q07/30 is where you are in
    //   the session; #067 is the number to look up in the printed book. Without
    //   it section 6 (scattered questions) is unusable — and the answer is a
    //   function of the absolute number in EVERY section.
    tft.setTextColor(C_TEXT, C_BG);
    tft.setTextDatum(TC_DATUM);
    snprintf(buf, sizeof(buf), "#%03d", pb_game_question(&game));
    tft.drawString(buf, W / 2, 4);

    tft.setTextColor(game.attempt == 1 ? C_DIM : C_TRY, C_BG);
    tft.setTextDatum(TR_DATUM);
    snprintf(buf, sizeof(buf), "TENT %d/3", game.attempt);
    tft.drawString(buf, W - 6, 4);
    tft.drawFastHLine(0, 26, W, C_DIM);

    for (int i = 0; i < 4; i++) {
        int x = 8 + i * 58, y = 44, w = 50, h = 54;
        char c[2] = { (char)('A' + i), 0 };
        huge();
        if (i == answerSel) {
            tft.fillRect(x, y, w, h, C_SEL);
            tft.setTextColor(C_BG, C_SEL);
        } else {
            tft.drawRect(x, y, w, h, C_DIM);
            tft.setTextColor(C_TEXT, C_BG);
        }
        tft.setTextDatum(TC_DATUM);
        tft.drawString(c, x + w / 2, y + 6);
    }
    tft.setTextColor(C_DIM, C_BG);
    drawHints("< OK responde", "troca >", H - 18);
}

static void drawJudge()
{
    char buf[32];
    tft.fillScreen(C_BG);
    tft.setTextDatum(TC_DATUM);

    if (lastVerdict == PB_RIGHT) {
        tft.setTextColor(C_RIGHT, C_BG);
        centreFit("CERTO!", 30, W - 8, T_TITLE);
        small(); tft.setTextColor(C_TEXT, C_BG);
        snprintf(buf, sizeof(buf), "+%d pontos", pb_game_last_points(&game));
        centreFit(buf, 92, W - 8, T_SMALL);
    } else if (lastVerdict == PB_RETRY) {
        tft.setTextColor(C_WRONG, C_BG);
        centreFit("ERRADO", 30, W - 8, T_TITLE);
        tft.setTextColor(C_TRY, C_BG);
        snprintf(buf, sizeof(buf), "tentativa %d de 3", game.attempt);
        centreFit(buf, 92, W - 8, T_SMALL);
    } else {
        tft.setTextColor(C_WRONG, C_BG);
        medium(); centre("ERRADO", 8);
        tft.setTextColor(C_TEXT, C_BG);
        small(); centre("a certa era", 46);
        huge(); tft.setTextColor(C_TRY, C_BG);
        char c[2] = { pb_game_revealed(&game), 0 };
        centre(c, 68);
    }
}

static void drawScore()
{
    char buf[40];
    int norm = pb_game_normalized(&game);
    int band = pb_game_band(&game);
    tft.fillScreen(C_BG);
    small(); tft.setTextColor(C_DIM, C_BG);
    tft.setTextDatum(TL_DATUM);
    snprintf(buf, sizeof(buf), "FIM   LIVRO %02d  SECAO %d", game.book, game.section);
    tft.drawString(buf, 6, 4);
    tft.drawFastHLine(0, 26, W, C_DIM);

    tft.setTextColor(C_TEXT, C_BG);
    snprintf(buf, sizeof(buf), "%d", game.raw);
    centreFit(buf, 30, W - 8, T_TITLE);
    small(); tft.setTextColor(C_DIM, C_BG);
    snprintf(buf, sizeof(buf), "de 300      %d%%", norm);
    centreFit(buf, 84, W - 8, T_SMALL);
    tft.setTextColor(band == 0 ? C_RIGHT : (band == 3 ? C_WRONG : C_TRY), C_BG);
    centreFit(BANDS[band], 100, W - 8, T_MED);
    tft.fillRect(0, H - 5, (int)((long)W * norm / 100), 5,
                 band == 0 ? C_RIGHT : (band == 3 ? C_WRONG : C_TRY));
}

// Repaint only when something actually changed — a full 240x135 push is not free.
static void render()
{
    char sig[128];
    snprintf(sig, sizeof(sig), "%d|%d%d%d|%d|%d|%d|%d|%d|%d|%d|%d",
             (int)screen, digits[0], digits[1], digits[2], pos, answerSel,
             game.index, game.attempt, game.raw, (int)lastVerdict,
             lastScore, muted ? 1 : 0);
    if (lastDrawn == sig) { return; }
    lastDrawn = sig;

    switch (screen) {
    case SC_STANDBY:  drawStandby();  break;
    case SC_CODE:     drawCode();     break;
    case SC_BAD:      drawBad();      break;
    case SC_QUESTION: drawQuestion(); break;
    case SC_JUDGE:    drawJudge();    break;
    case SC_SCORE:    drawScore();    break;
    }
}

static void go(Screen s)
{
    screen = s;
    screenAt = millis();
    lastDrawn = "";
}

// ---- actions ---------------------------------------------------------------

static void startCode()
{
    digits[0] = digits[1] = 0;
    digits[2] = 0;                 // VALS[2] is "123456<", so index 0 is section 1
    pos = 0;
    go(SC_CODE);
}

static void commitCode()
{
    char v = valAt(pos, digits[pos]);

    if (v == '<') {                        // ERASE is a value, never a long press
        if (pos == 0) { go(SC_STANDBY); }
        else          { pos--; go(SC_CODE); }
        PLAY(SFX_STEP);
        return;
    }
    if (pos < 2) { pos++; go(SC_CODE); PLAY(SFX_OK); return; }

    {
        int book = (valAt(0, digits[0]) - '0') * 10 + (valAt(1, digits[1]) - '0');
        int section = valAt(2, digits[2]) - '0';

        if (book < 1) {
            badReason = "livro 00 nao existe";
            PLAY(SFX_BAD); go(SC_BAD); return;
        }
        // ⚠ Seeded from micros() at the confirm press. esp_random() is only a true
        //   RNG while RF is active, and this game must be correct with WiFi down;
        //   a human's press timing is real entropy and costs one line.
        if (!pb_game_start(&game, book, section, (unsigned long long)micros())) {
            badReason = "codigo invalido";
            PLAY(SFX_BAD); go(SC_BAD); return;
        }
        answerSel = 0;
        PLAY(SFX_OK);
        go(SC_QUESTION);
    }
}

static void submitAnswer()
{
    lastVerdict = pb_game_answer(&game, (char)('A' + answerSel));

    // ⚠ PB_IGNORED changes nothing and must never look like a wrong answer.
    if (lastVerdict == PB_IGNORED) { return; }

    if (lastVerdict == PB_RIGHT)      { PLAY(SFX_RIGHT);  }
    else if (lastVerdict == PB_RETRY) { PLAY(SFX_WRONG);  }
    else                              { PLAY(SFX_REVEAL); }

    answerSel = 0;
    go(SC_JUDGE);
}

static void afterJudge()
{
    if (game.done) {
        lastScore = game.raw;
        lastBook = game.book;
        lastSection = game.section;
        prefs.putInt("score", lastScore);
        prefs.putInt("book", lastBook);
        prefs.putInt("sec", lastSection);
        switch (pb_game_band(&game)) {
        case 0: PLAY(SONG_0); break;
        case 1: PLAY(SONG_1); break;
        case 2: PLAY(SONG_2); break;
        default: PLAY(SONG_3); break;
        }
        go(SC_SCORE);
    } else {
        go(SC_QUESTION);
    }
}

static void onSelect()
{
    lastInput = millis();
    switch (screen) {
    case SC_CODE:
        digits[pos] = (digits[pos] + 1) % valCount(pos);
        PLAY(SFX_STEP);
        break;
    case SC_QUESTION:
        answerSel = (answerSel + 1) % 4;
        PLAY(SFX_STEP);
        break;
    default:
        break;
    }
}

static void onOk()
{
    lastInput = millis();
    switch (screen) {
    case SC_STANDBY:  PLAY(SFX_OK); startCode();  break;
    case SC_CODE:     commitCode();               break;
    case SC_QUESTION: submitAnswer();             break;
    case SC_SCORE:    PLAY(SFX_OK); go(SC_STANDBY); break;
    default:          break;   // SC_BAD and SC_JUDGE time out on their own
    }
}

// ---- input -----------------------------------------------------------------

static void inputTick()
{
    static bool okDown = false, selDown = false;
    static uint32_t okAt = 0, selAt = 0, nextRepeat = 0;

    uint32_t now = millis();
    bool ok  = (digitalRead(PIN_OK)     == LOW);
    bool sel = (digitalRead(PIN_SELECT) == LOW);

    // OK: fires on RELEASE, after a debounce. No hold gesture — GPIO0 is a
    // strapping pin and the sibling board's watchdog scar lives on holding it.
    if (ok && !okDown) { okDown = true; okAt = now; }
    else if (!ok && okDown) {
        okDown = false;
        if (now - okAt >= DEBOUNCE_MS) { onOk(); }
    }

    // SELECT: fires on PRESS, then auto-repeats while held (accelerating).
    // That is what makes 0-9 entry painless with a single button.
    if (sel && !selDown) {
        selDown = true; selAt = now;
        onSelect();
        nextRepeat = now + REPEAT_WAIT_MS;
    } else if (sel && selDown) {
        if (now >= nextRepeat) {
            // A long hold on STANDBY toggles mute instead of repeating.
            if (screen == SC_STANDBY) {
                muted = !muted;
                prefs.putBool("muted", muted);
                if (!muted) { PLAY(SFX_OK); }
                lastDrawn = "";
                nextRepeat = now + 1000;
            } else {
                onSelect();
                nextRepeat = now + ((now - selAt > REPEAT_ACCEL_MS) ? REPEAT_TURBO_MS
                                                                   : REPEAT_FAST_MS);
            }
        }
    } else if (!sel && selDown) {
        selDown = false;
    }
}

// ---- timers ----------------------------------------------------------------

static void timerTick()
{
    uint32_t now = millis();

    if (screen == SC_JUDGE) {
        uint32_t hold = (lastVerdict == PB_REVEAL) ? REVEAL_HOLD_MS : JUDGE_HOLD_MS;
        if (now - screenAt >= hold) { afterJudge(); }
        return;
    }
    if (screen == SC_BAD && now - screenAt >= BAD_HOLD_MS) { startCode(); return; }

    // ⚠ The game screen gets 10 minutes, the menus 3. See the constants block.
    uint32_t limit = (screen == SC_QUESTION) ? IDLE_GAME_MS : IDLE_MENU_MS;
    if (screen != SC_STANDBY && now - lastInput >= limit) { go(SC_STANDBY); }
}

// ---- setup / loop ----------------------------------------------------------

/* ── network selection, non-blocking ───────────────────────────────────────
   Alternates between the shared hotspot and the secrets.h network until one
   answers, then stops trying. Never scans, never waits, never blocks a frame.
   The hotspot goes first so a board carried somewhere else prefers the network
   that travels with it. */
/* ⚠⚠ THIS ALTERNATES ONCE, THEN STOPS. IT USED TO FLIP FOREVER, AND THAT TOOK A
   REAL BOARD OFF THE NETWORK.
   The first version swapped networks every 15 s for as long as it was
   disconnected. Association plus DHCP on a busy 2.4 GHz band routinely takes
   longer than that, so every swap ABORTED a connection that was still being
   negotiated — a board could flip between two APs indefinitely and never land on
   either. It looks harmless in the diff (a timer and an XOR) and it cost OTA
   access to a board sitting on someone's desk, recoverable only over USB.

   So: try the hotspot once, fall back to secrets.h once, then STOP TRYING and
   leave the radio alone. WiFi.setAutoReconnect(true) owns it from there, which
   is the code path the ESP-IDF actually tests. A board that lands on neither
   network plays the game exactly as well — that is the whole point of the
   design — and picks a network up on its next power cycle.

   ⚠ The lesson generalises past WiFi: RETRYING A SLOW OPERATION ON A TIMER
   SHORTER THAN THE OPERATION TAKES IS NOT A RETRY, IT IS A GUARANTEE OF
   FAILURE, and it is invisible in review because every individual line is
   reasonable. */
static uint8_t  wifiStage   = 0;   /* 0 = hotspot, 1 = secrets.h, 2 = done trying */
static uint32_t wifiTriedAt = 0;

static void wifiBeginStage()
{
    wifiTriedAt = millis();

    /* ⚠⚠ THE disconnect() IS LOAD-BEARING, AND ITS ABSENCE FAILED SILENTLY.
       The ESP-IDF REFUSES a credential change while the station is still
       associating, and it says so only on the serial console:

           E (43770) wifi:sta is connecting, cannot set config

       WiFi.begin() returns and the sketch carries on believing it switched
       networks. It did not. The board stayed on the first SSID — a hotspot that
       does not exist here — and no amount of retrying could ever move it,
       because every retry was refused by the same rule.

       Nothing above the serial line can see this: begin() has no useful return,
       the build is green, the binary is correct, and WiFi.status() reports
       DISCONNECTED either way, which is exactly what you would expect from a
       network that is genuinely out of range. It cost a board's OTA access and
       was found only by plugging in a USB cable and reading the log. */
    WiFi.disconnect(false, false);   /* release the station so config can be set */

    if (wifiStage == 0) WiFi.begin(PB_HOTSPOT_SSID, PB_HOTSPOT_PASS);
    else                WiFi.begin(WIFI_SSID, WIFI_PASS);
    Serial.printf("wifi: trying %s\n",
                  wifiStage == 0 ? PB_HOTSPOT_SSID : WIFI_SSID);
}

static void wifiTick()
{
    if (wifiStage >= 2) return;                       /* handed to autoreconnect */
    if (WiFi.status() == WL_CONNECTED) { wifiStage = 2; return; }
    if (millis() - wifiTriedAt < PB_WIFI_SWAP_MS) return;
    wifiStage++;
    if (wifiStage >= 2) {
        Serial.println("wifi: both tried; leaving it to autoreconnect");
        return;
    }
    wifiBeginStage();
}

/* ── say hello once ────────────────────────────────────────────────────────
   Everything the board sends lives here and in pbhello.h. Whole block compiles
   out at PB_PHONE_HOME 0. */
#if PB_PHONE_HOME

static char     helloUuid[PB_HELLO_UUID_LEN] = "";
static char     helloBody[PB_HELLO_MAX_PAYLOAD] = "";
static bool     helloDone     = false;   // one attempt per boot, win or lose
static uint32_t helloEarliest = 0;

/* The disclosure, shown once per payload version, BEFORE anything is sent.
   ⚠ BILINGUAL BECAUSE IT IS CONSENT, NOT DECORATION. The game is Portuguese —
   the printed books are Portuguese, so a player necessarily reads it — but the
   person who FLASHES a board is not always the person who plays it, and this
   project is being published to an international audience. A notice in a
   language the reader does not read is not a notice.

   ⚠ PRESENT TENSE, AND IT NAMES THIS VERSION ONLY. An earlier draft promised
   "nunca suas respostas". The planned multiplayer follow-up has a public
   scoreboard, which is answers leaving the device — so that promise would have
   been broken by its own roadmap. pbhello.h re-asks when the payload changes;
   this text simply never claims anything about a build that does not exist yet.

   ⚠ "sem criptografia" is TRUE and must stay true. The POST is plain HTTP: TLS
   costs flash on a partition already near full, and the payload is a random
   number plus a version string. If that ever changes to HTTPS, change this line
   in the same commit. */
static void helloDisclose()
{
    /* ⚠ The strings live in pbhello.h so hello-test/fit.c measures the SAME
       copy the panel draws. Re-typing them here would make that test prove only
       that someone typed them twice — and three of these lines DID clip before
       the measurement existed, including "how to turn it off" in both
       languages. Never inline them. */
    const char *const *page[2] = { PB_HELLO_PT, PB_HELLO_EN };

    for (int p = 0; p < 2; p++) {
        tft.fillScreen(C_BG);
        tft.setTextColor(C_SEL, C_BG);
        centreFit(page[p][0], 4, W - 8, T_MED);
        tft.setTextColor(C_TEXT, C_BG);
        /* 17px pitch, not 20: seven lines have to clear a 135px panel, and
           fit.c asserts the last one ends above it. */
        for (int i = 1; i < PB_HELLO_LINES; i++)
            centreFit(page[p][i], 26 + (i - 1) * 17, W - 8, T_SMALL);

        /* Held for a minimum before OK can skip, so one press cannot dismiss
           both pages — which would mean the English one was never displayed. */
        uint32_t t0 = millis();
        while (millis() - t0 < 5000) {
            soundTick();
            if (millis() - t0 > 1600 && digitalRead(PIN_OK) == LOW) break;
            delay(10);
        }
        while (digitalRead(PIN_OK) == LOW) delay(10);   // wait for release
    }
}

/* ⚠ RUNS ON ITS OWN TASK so loop() is never blocked by the network. HTTPClient
   is synchronous: a DNS lookup against a dead resolver stalls for seconds, and
   doing that inside loop() would freeze the buttons, the sound player and the
   idle timer. "Never blocks gameplay" has to be structural, not a short
   timeout that is usually fine. */
static void helloTask(void *)
{
    HTTPClient http;
    http.setConnectTimeout(4000);
    http.setTimeout(4000);
    http.setReuse(false);

    String url = String("http://") + PB_API_HOST + "/hello";
    if (http.begin(url)) {
        http.addHeader("Content-Type", "application/json");
        int code = http.POST((uint8_t *)helloBody, strlen(helloBody));
        Serial.printf("hello: POST %s -> %d\n", url.c_str(), code);
        http.end();
    } else {
        Serial.println("hello: begin() failed");
    }
    vTaskDelete(NULL);
}

static void helloTick()
{
    /* ⚠ ONE ATTEMPT PER BOOT. helloDone is set BEFORE the attempt, not after,
       so a failure can never re-enter. A board on a captive-portal WiFi would
       otherwise POST every pass of loop() forever — the exact runaway this
       ordering exists to make unrepresentable. */
    if (helloDone) return;
    if (WiFi.status() != WL_CONNECTED) return;
    if (millis() < helloEarliest) return;
    helloDone = true;

    /* ⚠ Generated only now, never in setup(): esp_random() is a true RNG only
       once the RF subsystem is running. Seeded before that it returns a
       pseudo-random sequence identical on every board — which would look
       perfectly valid and silently collapse the count to 1. */
    if (helloUuid[0] == '\0') {
        unsigned char rnd[16];
        for (int i = 0; i < 16; i++) rnd[i] = (unsigned char)(esp_random() & 0xFF);
        pb_hello_uuid4(rnd, helloUuid);
        prefs.putString("hello_id", helloUuid);
        Serial.printf("hello: new board id %s\n", helloUuid);
    }

    if (pb_hello_payload(helloUuid, PB_VERSION, helloBody, sizeof helloBody) == 0) {
        Serial.println("hello: payload would not fit — sending nothing");
        return;
    }
    /* ⚠ 16 KB, not 8: HTTPClient + WiFiClient + the TCP buffers live on THIS
       task's stack, and an overflow is a panic-reboot, not a failed request. */
    xTaskCreate(helloTask, "hello", 16384, NULL, 1, NULL);
}
#endif  /* PB_PHONE_HOME */

void setup()
{
    Serial.begin(115200);

    pinMode(PIN_OK, INPUT_PULLUP);
    pinMode(PIN_SELECT, INPUT);   // ⚠ input-only pin: no internal pull-up exists

    tft.init();
    tft.setRotation(1);
    tft.fillScreen(C_BG);

    // ⚠ AFTER tft.init(): it re-claims its backlight pin as a plain output and
    //   would clobber a PWM mux attached before it.
    ledcAttach(PIN_BL, 5000, 8);
    ledcWrite(PIN_BL, BL_ON);
#if PB_BUZZER_PIN >= 0
    ledcAttach(PB_BUZZER_PIN, 2000, 10);
    ledcWriteTone(PB_BUZZER_PIN, 0);
#endif

    pb_init();

    prefs.begin("pensebem", false);
    muted       = prefs.getBool("muted", false);
    lastScore   = prefs.getInt("score", -1);
    lastBook    = prefs.getInt("book", 0);
    lastSection = prefs.getInt("sec", 0);

#if PB_PHONE_HOME
    /* The id persists across reboots — a board is counted once, not once per
       power cycle. Generated lazily in helloTick(), not here: see the RNG note
       there. */
    prefs.getString("hello_id", helloUuid, sizeof helloUuid);
    if (!pb_hello_valid(helloUuid)) helloUuid[0] = '\0';
#endif

    // WiFi NEVER blocks. The game must work with every AP down.
    WiFi.mode(WIFI_STA);
    WiFi.setAutoReconnect(true);
    wifiStage = 0;              // hotspot first, secrets.h as the fallback
    wifiBeginStage();
    MDNS.begin(HOSTNAME);
    ArduinoOTA.setHostname(HOSTNAME);
    ArduinoOTA.setPassword(OTA_PASS);
    ArduinoOTA.onStart([]() { soundStop(); tft.fillScreen(C_BG);
                              medium(); tft.setTextColor(C_SEL, C_BG);
                              centre("ATUALIZANDO", 50); });
    ArduinoOTA.onEnd([]()   { centre("OK", 90); });
    ArduinoOTA.begin();

    // Serial parity dump — diff against the Go backend's
    // GET /api/v1/books/{n}/answers. Two implementations agreeing is a real
    // check; a header agreeing with itself is not.
    Serial.printf("\npense-bem %s  |  offsets popped=%d (must be %d)\n",
                  PB_VERSION, pb_offsets_popped(), PB_OFFSETS);
    for (int b = 1; b <= 99; b += 49) {
        Serial.printf("book %02d: ", b);
        const unsigned char *k = pb_answer_key(b);
        for (int q = 0; q < PB_QUESTIONS; q++) { Serial.write(k[q]); }
        Serial.println();
    }

    /* ⚠ The splash doubles as the buzzer wiring self-test the boot beep used to
       be: four rising notes as the boxes land. Silent board + "SOM LIGADO" on
       standby still means check the wiring. */
    playSplash();

#if PB_PHONE_HOME
    /* ⚠ AFTER the splash and BEFORE anything is sent. Shown once per payload
       version, so a change to what is sent re-opens the question rather than
       inheriting an answer given about a different message. */
    if (pb_hello_needs_disclosure(prefs.getInt("hello_ok", 0))) {
        helloDisclose();
        prefs.putInt("hello_ok", PB_HELLO_PAYLOAD_VERSION);
    }
    /* A short grace period so the first POST does not race WiFi association
       and burn this boot's single attempt on a stack that was not ready. */
    helloEarliest = millis() + 4000;
#endif

    lastInput = millis();
    go(SC_STANDBY);
}

void loop()
{
    ArduinoOTA.handle();
    inputTick();
    timerTick();
    soundTick();
    render();
    wifiTick();    /* retimes a begin(); never scans, never waits */
#if PB_PHONE_HOME
    helloTick();   /* returns immediately after the single attempt is made */
#endif
    delay(10);
}
